import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sample data
df = pd.read_csv('snapshot_dynamo_sitedata.csv')

# deal with issues saving negative numbers
df['energy_consumed_kwh'] = df['energy_consumed_kwh'].str.replace("'", "").astype(float)
df['energy_generated_kwh'] = df['energy_generated_kwh'].str.replace("'", "").astype(float)

# Calculate averages per site
avg_by_site = df.groupby('site_id').agg({
    'energy_consumed_kwh': 'mean',
    'energy_generated_kwh': 'mean'
}).reset_index()

# Reshape data for seaborn
plot_data = pd.melt(avg_by_site, 
                    id_vars=['site_id'],
                    value_vars=['energy_consumed_kwh', 'energy_generated_kwh'],
                    var_name='Energy Flow',
                    value_name='Avg kWh')

# Create the plot
plt.figure(figsize=(10, 6))
sns.barplot(data=plot_data, 
            x='site_id', 
            y='Avg kWh',
            hue='Energy Flow')

# Customize the plot
plt.title('Avg Energy Consumed vs Generated by Site', pad=20)
plt.xlabel('Site ID')
plt.ylabel('Energy (kWh)')

plt.show()